# Generated by Django 5.2.13 on 2026-05-15 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_produto_imagem'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('buyer', 'Comprador'), ('seller', 'Vendedor')], default='buyer', max_length=20),
        ),
    ]
