# Generated by Django 5.2.13 on 2026-06-19 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_user_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='itempedido',
            name='cor',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='itempedido',
            name='imagem_url',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='itempedido',
            name='nome',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='itempedido',
            name='tamanho',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
