# Generated by Django 5.2.12 on 2026-04-01 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_user_passage_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=100)),
                ('nome', models.CharField(max_length=60)),
                ('preco', models.DecimalField(decimal_places=2, max_digits=10)),
                ('marca', models.CharField(max_length=60)),
                ('condicao', models.CharField(choices=[('novo', 'Novo'), ('seminovo', 'Seminovo'), ('usado', 'Usado')], default='novo', max_length=10)),
            ],
        ),
    ]
