# Generated by Django 5.2.12 on 2026-04-08 18:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_buscaimagem'),
    ]

    operations = [
        migrations.AddField(
            model_name='buscaimagem',
            name='produto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.produto'),
        ),
    ]
