# Generated by Django 5.2.13 on 2026-08-26 17:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_pedido_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itempedido',
            name='produto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='itens_pedido', to='core.produto'),
        ),
        migrations.AlterField(
            model_name='itempedido',
            name='quantidade',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
