# Generated by Django 5.2.13 on 2026-08-26 17:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_itempedido_produto_alter_itempedido_quantidade'),
    ]

    operations = [
        migrations.AddField(
            model_name='venda',
            name='vendedor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='vendas', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='venda',
            name='pedido',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='venda', to='core.pedido'),
            preserve_default=False,
        ),
    ]
