# Generated by Django 5.2.13 on 2026-08-27 14:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_venda_vendedor_alter_venda_pedido'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='produtos', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name='itempedido',
            constraint=models.UniqueConstraint(fields=('pedido', 'produto'), name='produto_unico_por_pedido'),
        ),
    ]
