# Generated by Django 5.2.12 on 2026-04-09 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_favorito'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='favorito',
            unique_together={('usuario', 'produto')},
        ),
    ]
