# Generated by Django 5.2.13 on 2026-08-27 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_produto_user_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pedido',
            old_name='data_pedido',
            new_name='criado_em',
        ),
        migrations.AddField(
            model_name='pedido',
            name='atualizado_em',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='status',
            field=models.CharField(choices=[('PENDENTE', 'Pendente'), ('AGUARDANDO_PAGAMENTO', 'Aguardando pagamento'), ('PAGO', 'Pago'), ('CANCELADO', 'Cancelado')], default='PENDENTE', max_length=30),
        ),
    ]
