# Generated by Django 5.2.13 on 2026-08-27 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_rename_data_pedido_pedido_criado_em_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='mercado_pago_preference_id',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
