# Generated by Django 5.2.17 on 2026-09-11 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_pedido_mercado_pago_preference_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='mercado_pago_payment_id',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='pedido',
            name='mercado_pago_status',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='pedido',
            name='mercado_pago_status_detail',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='pedido',
            name='pago_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
