# Generated by Django 5.2.12 on 2026-04-13 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_historicopesquisa'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historicopesquisa',
            options={'ordering': ['-data_pesquisa']},
        ),
    ]
